trigger:
  branches:
    include:
    - test2
jobs:
###########################################
- job: Linux
###########################################
  variables:
    COMPILER: gcc
  pool: 'linux-gpu-pool'
  strategy:
    maxParallel: 6
    matrix:
      cuda:
        TASK: cuda
  steps:
  - script: |
      echo "##vso[task.setvariable variable=BUILD_DIRECTORY]$BUILD_SOURCESDIRECTORY"
      echo "##vso[task.setvariable variable=OS_NAME]linux"
      echo "##vso[task.setvariable variable=AZURE]true"
      echo "##vso[task.setvariable variable=LGB_VER]$(head -n 1 VERSION.txt)"
      echo "##vso[task.prependpath]$CONDA/bin"
      AMDAPPSDK_PATH=$BUILD_SOURCESDIRECTORY/AMDAPPSDK
      echo "##vso[task.setvariable variable=AMDAPPSDK_PATH]$AMDAPPSDK_PATH"
      LD_LIBRARY_PATH=$AMDAPPSDK_PATH/lib/x86_64:$LD_LIBRARY_PATH
      echo "##vso[task.setvariable variable=LD_LIBRARY_PATH]$LD_LIBRARY_PATH"
      echo "##vso[task.setvariable variable=OPENCL_VENDOR_PATH]$AMDAPPSDK_PATH/etc/OpenCL/vendors"
    displayName: 'Set variables'
  - script: |
      curl https://get.docker.com | sudo CHANNEL=stable sh
      curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
      curl -s -L https://nvidia.github.io/nvidia-docker/ubuntu18.04/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
      sudo apt-get update && sudo apt-get install -y nvidia-docker2
      sudo sed -i 's/^#root/root/' /etc/nvidia-container-runtime/config.toml
      sudo tee /etc/modules-load.d/ipmi.conf <<< "ipmi_msghandler"
      sudo tee /etc/modprobe.d/blacklist-nouveau.conf <<< "blacklist nouveau"
      sudo tee -a /etc/modprobe.d/blacklist-nouveau.conf <<< "options nouveau modeset=0"
      sudo update-initramfs -u
      sudo docker run -d --privileged --pid=host -v /run/nvidia:/run/nvidia:shared --restart=unless-stopped nvidia/driver:418.40.04-ubuntu18.04 --accept-license
      sudo docker run --rm --runtime=nvidia nvidia/cuda:9.2-base nvidia-smi
  - bash: $(Build.SourcesDirectory)/.ci/setup.sh
    displayName: Setup
  - bash: $(Build.SourcesDirectory)/.ci/test.sh
    displayName: Test

